[platformio]
default_envs = usb

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  fastled/FastLED

[env:usb]

[env:ota]
upload_protocol = espota
upload_port = dragon-light.local
upload_flags =
  --auth=${sysenv.DRAGON_LIGHT_OTA_PASSWORD}
